### ISSUE TITLE
check media-type attribute.

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/nexus-bbp-domains#155]
For certain property, we want to say that the resources being is of a certain media-type.
When that property is being set, we want to make sure that it belongs to a certain list of media-type defined in the schema.

**Comment by MFSY** [comment]
Hi,
I would suggest the following strategy to start with media type validation:

- Users should be allowed to use string as media type value like:

```json
"mediaType":"application/json"
```
This corresponds to a widely adopted way of using media types. 

* The first step for validation would be to check that the providing string match IANA media type structure. The media type pattern can be seen in [nexus/core/distribution](https://github.com/BlueBrain/nexus-kg/blob/master/modules/kg-schemas/src/main/resources/schemas/nexus/core/distribution/v0.1.0.json) and in [nexus/core/mediatype](https://github.com/MFSY/nexus-bbp-domains/blob/9f8d13fdbdf6bbc4f6e75d5a6efc69dfa6737b2b/modules/kg-bbp-schemas/src/main/resources/schemas/nexus/core/mediatype/v0.1.0.json) schemas.

* The second step would be to check that a provided media type is in a given list. Any schema can define a list of accepted values for a property. You can extends the distribution schema in you custom entity schema like this:


```json
{
....
"shapes": [
    {
      "@id": "this:DistributionShape",
      "@type": "sh:NodeShape",
      "and": [
        {
          "node":"{{base}}/schemas/nexus/core/distribution/v0.1.0/shapes/DistributionShape"
        },
        {
          "property": [
            {
              "path": "schema:mediaType",
              "in": ["application/pdf","application/json"]
            }
          ]
        }
      ]
    }
  ]
}
```

But this strategy comes with downsides:
* every time a new media type is added than a new schema version is needed.  
* regex based validation is slow.

We can improve this strategy later by relying on types for media types.
