### ISSUE TITLE
description of a media type.

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/nexus-bbp-domains#156]
We want to be able to describe a media-type. For instance, we want to say that 'BBP/AIBS' media type (our own media type) is defined in a particular URL. 
or 'morphology/swc' is defined in another particular URL

**Comment by MFSY** [comment]
I would suggest to follow the IANA spec when defining a custom media type. You can checkout the [form](https://www.iana.org/form/media-types) they recommend to use when registering a media type. The goal is not for you to register the media types you're interested in IANA but to see what is expected to be part of a media type description.

For example, all media types start with one of application|audio|font|image|message|model|multipart|text|video .
