### ISSUE TITLE
register media-type

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/nexus-bbp-domains#157]
We want to be able to create our own media-types,that are not part of IANA.

**Comment by MFSY** [comment]
The [bbp/core/mediatype](https://github.com/MFSY/nexus-bbp-domains/blob/9f8d13fdbdf6bbc4f6e75d5a6efc69dfa6737b2b/modules/bbp-core/src/main/resources/schemas/bbp/core/mediatype/v0.1.0.json) schema (to be merged) can be used to register a media type consistent with IANA specification.
