### ISSUE TITLE
Add StimulusOntologyTermShape and EcodeOntologyTermShape in the typedlabeledontologyterm schema

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-bbp-domains#97]
The two shapes bbp/core/typedlabeledontologyterm/StimulusOntologyTermShape and bbp/core/typedlabeledontologyterm/EcodeOntologyTermShape are referenced in the /bbp/electrophysiology/stimulusexperiment [schema](https://github.com/annakristinkaufmann/nexus-bbp-domains/blob/1d0fb2de5dd176e9d80e47608d7e174e9212cf54/modules/bbp-electrophysiology/src/main/resources/schemas/bbp/electrophysiology/stimulusexperiment/v0.1.0.json) without being defined in bbp/core/typedlabeledontologyterm schema.

**Comment by annakristinkaufmann** [comment]
closed via #87
