### ISSUE TITLE
Use one consistent way of adding BrainLocation properties in entities

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-bbp-domains#99]

**Comment by annakristinkaufmann** [comment]
After discussing different possibilities, it was agreed to add brainLocation properties in the following way:

use brainLocation property shape with BrainLocationShape as node in schemas:
{
"property":
[
"path": "nsg:brainLocation",
"node": "bbplocsh:BrainLocationShape"
]
}
